### ISSUE TITLE
[Feat] Add Contact Form Page

### ISSUE THREAD

**Issue by lgastineau** [anders-swanson/site#4]
Form should contain the following fields:

- Your Name
- Your Email
- Subject
- Your Message

**Comment by anders-swanson** [comment]
this form additionally requires:
- SMTP server configuration
- CAPTCHA or other challenge to prevent SMTP server abuse

Form will be added on burger menu.

**Comment by anders-swanson** [comment]
Fixed by: https://github.com/anders-swanson/site/commit/00db74230fedc8d06b03c478b21f5f5019629bf5
